POST http://localhost:5000/username
Content-Type: application/json

{
    "post": "nicole"
}

###

POST http://localhost:5000/roomadduser
Content-Type: application/json

{
    "nickName": "rossmaider",
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST http://localhost:5000/roomadduser
Content-Type: application/json

{
    "nickName": "JohnSmith",
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST http://localhost:5000/configurequiz
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "category": ["animals", "brain teasers"],
    "numOfQuestions": 3,
    "maxTime": 5
}

###

POST http://localhost:5000/roomallnicknames
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST http://localhost:5000/startroom
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST  http://localhost:5000/questions
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST http://localhost:5000/questionresponse
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "nickname": "nicole",
    "response": "Sloth",
    "questionnumber": 1,
    "individualtime": 1
}

###

POST http://localhost:5000/questionresponse
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "nickname": "nicole",
    "response": "Snail",
    "questionnumber": 2,
    "individualtime": 1
}

###

POST http://localhost:5000/questionresponse
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "nickname": "nicole",
    "response": "Felis silvestris catus",
    "questionnumber": 3,
    "individualtime": 1
}

###

POST http://localhost:5000/questionresponse
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "nickname": "JohnSmith",
    "response": "Sloth",
    "questionnumber": 1,
    "individualtime": 1
}

###

POST http://localhost:5000/questionresponse
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "nickname": "JohnSmith",
    "response": "Fox",
    "questionnumber": 2,
    "individualtime": 1
}

###

POST http://localhost:5000/questionresponse
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6",
    "nickname": "JohnSmith",
    "response": "Felis silvestris catus",
    "questionnumber": 3,
    "individualtime": 1
}

###

POST http://localhost:5000/history
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST http://localhost:5000/playagain
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6"
}

###

POST http://localhost:5000/roomallplayers
Content-Type: application/json

{
    "roomCode": "8c833fb8a338557c69c6"
}