POST http://localhost:5000/username
Content-Type: application/json

{
    "post": "rossmaider"
}

###

POST http://localhost:5000/roomadduser
Content-Type: application/json

{
    "nickName": "rossmaider",
    "roomCode": "e56fb39f6d5e740acab5"
}

###

POST http://localhost:5000/roomadduser
Content-Type: application/json

{
    "nickName": "JohnSmith",
    "roomCode": "e56fb39f6d5e740acab5"
}

###

GET  http://localhost:5000/questions
Content-Type: application/json

{
    "roomCode": "5200d9c15f41f7020009"
}

###

POST http://localhost:5000/roomallplayers
Content-Type: application/json

{
    "roomCode": "912407b7d9a40cbb8892"
}

###

POST http://localhost:5000/roomallnicknames
Content-Type: application/json

{
    "roomCode": "912407b7d9a40cbb8892"
}

###

POST http://localhost:5000/startroom
Content-Type: application/json

{
    "roomCode": "92547178ac535cbe8026",
    "category": "'animals'",
    "numOfQuestions": 2
}