# Use postgres/example user/password credentials
version: '3.3'
services:
  
  database:
    image : postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: aylin
      POSTGRES_PASSWORD: aylin
      POSTGRES_DB: Uni_db
    volumes:
        - Data_Base/DataSet
volumes: 
  database-data: